minimumReleaseAgeExclude:
  - solid-use@1.0.0-next.3
  - terracotta@2.0.0-next.9
  - '@devframes/agentic@1.0.0'
  - '@devframes/hub-ui@1.0.0'
  - '@devframes/hub@1.0.0'
  - '@devframes/json-render-ui@1.0.0'
  - '@devframes/json-render@1.0.0'
  - '@devframes/plugin-inspect@1.0.0'
  - '@devframes/plugin-messages@1.0.0'
  - '@devframes/plugin-terminals@1.0.0'
  - '@devframes/service-open@1.0.0'
  - '@devframes/vite@1.0.0'
  - '@vitejs/devtools-kit@0.7.5'
  - '@vitejs/devtools@0.7.5'
  - devframe@1.0.0
onlyBuiltDependencies:
  - esbuild
