minimumReleaseAgeExclude:
  - solid-use@1.0.0-next.3
  - terracotta@2.0.0-next.9
  - '@solidjs/compiler-darwin-arm64@2.0.0-rc.13'
  - '@solidjs/compiler-darwin-x64@2.0.0-rc.13'
  - '@solidjs/compiler-linux-arm64-gnu@2.0.0-rc.13'
  - '@solidjs/compiler-linux-x64-gnu@2.0.0-rc.13'
  - '@solidjs/compiler-wasm32-wasi@2.0.0-rc.13'
  - '@solidjs/compiler-win32-x64-msvc@2.0.0-rc.13'
  - '@solidjs/compiler@2.0.0-rc.13'
  - '@solidjs/signals@2.0.0-rc.13'
  - '@solidjs/web@2.0.0-rc.13'
  - solid-js@2.0.0-rc.13
onlyBuiltDependencies:
  - esbuild
